// AUTO-GENERATED by scripts/inline-migrations.mjs  DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @emploke/_template db:generate`.
// Source of truth: packages/_template/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `__entities__` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `__entities___name_idx` ON `__entities__` (`name`);\n"
    ],
    bps: true,
    folderMillis: 1,
    hash: "b7e4ab1c33f13ddf621383d2abe300c7845af7a9a86e425c321d23b691ce5f35",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations___PKG__`.
 * Each entity pkg owns its own journal table so multiple pkgs sharing
 * the same `workspace.db` file don't trip drizzle's global
 * `folderMillis` watermark check. Naming convention locked: every
 * emploke pkg uses `__drizzle_migrations_<pkg>`, no exceptions.
 */
export function apply__Entity__Migrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations___PKG__",
  });
}
