// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm db:generate` (per pkg) or `pnpm bundle` (whole repo).
// Source of truth: packages/task/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

export interface InlinedMigration {
  readonly name: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly InlinedMigration[] = Object.freeze([
  {
    "name": "0000_nasty_hawkeye.sql",
    "sql": "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text,\n\t`status` text NOT NULL,\n\t`brief` text NOT NULL,\n\t`details` text,\n\t`origin` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`ended_at` text,\n\t`success` text,\n\t`failure` text,\n\t`cancellation` text,\n\t`metadata` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `tasks_agent_idx` ON `tasks` (`agent`);--> statement-breakpoint\nCREATE INDEX `tasks_runtime_idx` ON `tasks` (`runtime`);--> statement-breakpoint\nCREATE INDEX `tasks_status_idx` ON `tasks` (`status`);--> statement-breakpoint\nCREATE INDEX `tasks_origin_idx` ON `tasks` (`origin`);"
  }
]) as readonly InlinedMigration[];
