// AUTO-GENERATED by scripts/inline-migrations.mjs  DO NOT EDIT BY HAND.
// Regenerate with `pnpm bundle` or `pnpm -F @emploke/workflows db:generate`.
// Source of truth: packages/workflows/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import type { MigrationMeta } from "drizzle-orm/migrator";

export const MIGRATIONS: readonly MigrationMeta[] = [
  {
    sql: [
      "CREATE TABLE `workflows` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`brief` text NOT NULL,\r\n\t`details` text,\r\n\t`status` text NOT NULL,\r\n\t`outcome` text,\r\n\t`metadata` text DEFAULT '{}' NOT NULL,\r\n\t`created_at` text NOT NULL,\r\n\t`started_at` text,\r\n\t`archived_at` text\r\n);\r\n",
      "\r\nCREATE TABLE `workflow_nodes` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`workflow_id` text NOT NULL,\r\n\t`type` text DEFAULT 'task' NOT NULL,\r\n\t`status` text NOT NULL,\r\n\t`spec` text DEFAULT '{}' NOT NULL,\r\n\t`data` text DEFAULT '{}' NOT NULL,\r\n\t`created_at` text NOT NULL,\r\n\t`ready_at` text,\r\n\t`running_at` text,\r\n\t`ended_at` text\r\n);\r\n",
      "\r\nCREATE INDEX `workflow_nodes_workflow_idx` ON `workflow_nodes` (`workflow_id`);",
      "\r\nCREATE INDEX `workflow_nodes_status_idx` ON `workflow_nodes` (`workflow_id`,`status`);",
      "\r\nCREATE TABLE `workflow_edges` (\r\n\t`workflow_id` text NOT NULL,\r\n\t`from_node_id` text NOT NULL,\r\n\t`to_node_id` text NOT NULL,\r\n\tPRIMARY KEY(`workflow_id`, `from_node_id`, `to_node_id`)\r\n);\r\n",
      "\r\nCREATE INDEX `workflow_edges_from_idx` ON `workflow_edges` (`workflow_id`,`from_node_id`);",
      "\r\nCREATE INDEX `workflow_edges_to_idx` ON `workflow_edges` (`workflow_id`,`to_node_id`);\r\n"
    ],
    bps: true,
    folderMillis: 1,
    hash: "d53fece24e28444f0a986d78efe0f247498d6eec0abeaeb955399e9732e3c25e",
  },
];

/**
 * Run drizzle's official migration applier against `db`. Thin typed
 * shim over drizzle's `@internal` `dialect` + `session` props (same
 * props drizzle's own `migrate()` from `drizzle-orm/better-sqlite3/migrator`
 * touches) so consumers don't repeat the cast.
 *
 * **Per-pkg `migrationsTable`**: `__drizzle_migrations_workflows`.
 * Each entity pkg owns its own journal table so multiple pkgs sharing
 * the same `workspace.db` file don't trip drizzle's global
 * `folderMillis` watermark check. Naming convention locked: every
 * emploke pkg uses `__drizzle_migrations_<pkg>`, no exceptions. See
 * `docs/architecture.md` Migrations section.
 */
export function applyWorkflowsMigrations<T extends Record<string, unknown>>(
  db: BetterSQLite3Database<T>,
): void {
  const internals = db as unknown as {
    dialect: { migrate(m: readonly MigrationMeta[], s: unknown, c?: { migrationsTable: string }): void };
    session: unknown;
  };
  internals.dialect.migrate(MIGRATIONS, internals.session, {
    migrationsTable: "__drizzle_migrations_workflows",
  });
}
