// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm db:generate` (per pkg) or `pnpm bundle` (whole repo).
// Source of truth: packages/workspace/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

export interface InlinedMigration {
  readonly name: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly InlinedMigration[] = Object.freeze([
  {
    "name": "0000_cooing_slyde.sql",
    "sql": "CREATE TABLE `workspaces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`workspace_dir` text NOT NULL,\n\t`name` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`last_opened_at` text\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `workspaces_workspace_dir_unique` ON `workspaces` (`workspace_dir`);"
  }
]) as readonly InlinedMigration[];
