// AUTO-GENERATED by scripts/inline-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerate with `pnpm db:generate` (per pkg) or `pnpm bundle` (whole repo).
// Source of truth: packages/session/drizzle/*.sql.
// biome-ignore-all format: keep generator output stable across runs.
// biome-ignore-all lint: generated, may include unused/long lines.

export interface InlinedMigration {
  readonly name: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly InlinedMigration[] = Object.freeze([
  {
    "name": "0000_zippy_martin_li.sql",
    "sql": "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`agent` text NOT NULL,\n\t`runtime` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`runtime_session_id` text,\n\t`last_launch_mode` text\n);\n--> statement-breakpoint\nCREATE INDEX `sessions_agent_idx` ON `sessions` (`agent`);"
  }
]) as readonly InlinedMigration[];
